In [18]:
# Imports
import pandas as pd
from tensorflow import keras
import numpy as np
import json as json
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

ModuleNotFoundError: No module named 'keras.models'

In [14]:
# Loading the data from CSV into panadas dataframe
df = pd.read_csv (r'..\data\topFiveFeats211207.csv', sep=',')
#fashion_train_df = pd.read_csv('input/fashion-mnist_train.csv',sep=',')

# printing
print(df)

            3m        1m  reportedEPS  totalNonCurrentAssets  \
0     0.033148  0.064982    -0.071429              -0.001280   
1     0.121244  0.076218    -0.166667               0.078745   
2    -0.079433 -0.005502     1.301370               0.109743   
3     0.145756 -0.060012     0.123077               0.016336   
4    -0.682538  0.165132     0.015625               0.003578   
...        ...       ...          ...                    ...   
3559  0.051477 -0.038944    -0.298824              -0.022708   
3560  0.247348 -0.000558     0.133333               0.004647   
3561  0.038863 -0.041763     0.250000               0.003391   
3562  0.105128 -0.021795     0.006711              -0.053751   
3563  0.087866 -0.032775     0.192000               0.002413   

      depreciationAndAmortization  currentAccountsPayable  profitLoss  
0                        0.012513                0.007028   -0.079814  
1                        0.049137               -0.371503   -0.178230  
2              

In [15]:
# Making the toy model with tensorflow
model = tf.keras.models.Sequential()

# Layers
model.add(tf.keras.layers.Dense(units = 8, activation = 'relu', input_dim=5))
model.add(tf.keras.layers.Dense(units = 1, activation = 'linear'))

AttributeError: module 'tensorflow.keras' has no attribute 'models'

In [16]:
# compiling the model
opt = keras.optimizers.Adam(learning_rate=0.5)
model.compile(loss = 'mean_squared_error', optimizer = opt, metrics=['accuracy'])

AttributeError: module 'keras' has no attribute 'optimizers'

In [19]:
# Declaring the label
label = df["1m"].to_numpy()

#Declaring the features
column_features = ["reportedEPS","totalNonCurrentAssets","depreciationAndAmortization","currentAccountsPayable", "profitLoss"]
features = df[column_features].to_numpy()


In [20]:
# Normalization
row_sums = features.sum(axis=1)
norm_features = features / row_sums[:, np.newaxis]

#print
print(norm_features)
 

[[ 0.53713419  0.00962241 -0.0940993  -0.05284735  0.60019006]
 [ 0.28319767 -0.13380321 -0.08349339  0.63125322  0.30284571]
 [ 0.62807945  0.05296535 -0.0064303   0.24590186  0.07948363]
 ...
 [ 1.30644984  0.01772208 -1.24249775  0.26958094  0.64874489]
 [ 0.08182301 -0.65530615 -0.56894267  0.62892401  1.5135018 ]
 [ 0.51407511  0.00645953  0.00895476  0.13812166  0.33238894]]


C:\Users\Asus\AppData\Local\Temp/ipykernel_10292/4207361803.py:3: RuntimeWarning: invalid value encountered in true_divide
  norm_features = features / row_sums[:, np.newaxis]


In [21]:
# fitting the model
model.fit(norm_features, label, epochs = 10, batch_size = 32)

NameError: name 'model' is not defined

In [22]:
 # Model evaluation
test_loss, test_acc = model.evaluate(norm_features, label)

# Printing
print('\nTest accuracy:', test_acc)

NameError: name 'model' is not defined

In [23]:
# prediction
predictions = model.predict(norm_features)
print(predictions)

NameError: name 'model' is not defined